### ISSUE TITLE
Send push notification to all users

### ISSUE THREAD

**Issue by yaofong** [brozot/Laravel-FCM#1]
Hi,

Thanks for this amazing plugin.

Would like to know how do I push notifications to all users using my app?

**Comment by brozot** [comment]
Hello thank's for your question.

Get all your tokens in your database and put them in a array
And send notifications with the Facade and the method `FCM::sendTo(arrayOfTokens, options, notification, data)`

Following a example that I have used in my app:

```
$tokens = Device::pluck('fcm_token')->toArray(); // Device is a Eloquent model that contains tokens
        
$optionBuilder = new OptionsBuilder();
$optionBuilder->setCollapseKey('cat_detected');

$notification = new PayloadNotificationBuilder(null);
$notification->setIcon('cat_notification')
                     ->setSound('default');

$notification->setTitleLocationKey('notification__title__cat_detected');
$notification->setBodyLocationKey('notification__body__cat_detected');
$notification->setBodyLocationArgs("[\"$detectionDate\", \"$detectionHour\"]");

$response = FCM::sendTo($tokens, $optionBuilder->build(), $notification->build());
```
I hope this answer will help you, and please not hesitate to contact me again if it's not working for you.

**Comment by Macias67** [comment]
Hi, this way is asynchronous method? Actually I use this in an event in Laravel 5.2, what do you think?
