### ISSUE TITLE
Is it possible to set priority

### ISSUE THREAD

**Issue by kiwo12345** [brozot/Laravel-FCM#10]
Thanks for sharing this!

I wonder if its possible to set the priority of a message?

https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message 

Thanks,

**Comment by brozot** [comment]
Hi,

You can set the priority in this way :

 ```php
$priority = 'high' // or 'normal'
$optionBuiler = new OptionsBuilder();
$optionBuiler->setPriority($priority);
$optionBuiler->build();
```

or also 

```php
$optionBuiler = new OptionsBuilder();
$optionBuilder->setPriority(OptionsPriorities::high);
$optionBuiler->build();
```

I hope that will help you 

You can fin more informations on the api references : 
https://github.com/brozot/Laravel-FCM/tree/master/doc

Best

**Comment by kiwo12345** [comment]
Thank you!

**Comment by isnopitag** [comment]
> 
> 
> Hi,
> 
> You can set the priority in this way :
> 
> ```
> $priority = 'high' // or 'normal'
> $optionBuiler = new OptionsBuilder();
> $optionBuiler->setPriority($priority);
> $optionBuiler->build();
> ```
> 
> or also
> 
> ```
> $optionBuiler = new OptionsBuilder();
> $optionBuilder->setPriority(OptionsPriorities::high);
> $optionBuiler->build();
> ```
> 
> I hope that will help you
> 
> You can find more information on the api references :
> https://github.com/brozot/Laravel-FCM/tree/master/doc
> 
> Best

Sorry but its $optionBuilder...
