### ISSUE TITLE
numberTokensSuccess: 0, numberTokensFailure: 3

### ISSUE THREAD

**Issue by MikeeBulalacao** [brozot/Laravel-FCM#101]
Can someone please tell me how to fix this? When I check my code, numberTokensSuccess: 0, numberTokensFailure: 3 shows up, and I don't understand why. 

I am using the code in "Sending a Downstream Message to Multiple Devices". I am testing my code in Postman, and what does tokensToDelete mean? Why do I have to delete it? Thank you so much. Sorry, I am a beginner here.

**Comment by litus92** [comment]
same error here

**Comment by tanvirstreet** [comment]
@MikeeBulalacao  did u find any solution yet ?

**Comment by Krunal244** [comment]
Send token one by one instead of array 
so use foreach for send token like this

foreach ($tokens as $token) {
    		$downstreamResponse = FCM::sendTo($token, $option, $notification, $data);
    	}
I don't know why array not working. But above solution working fine.

**Comment by MikeeBulalacao** [comment]
I'm sorry I replied so late. Yes I already fixed it. 

My code for getting the tokens is;
$tokens = DriverDeviceToken::whereIn('user_type', $userType)->pluck('token')->toArray();

Then send the data to tokens:
$res = FCM::sendTo($tokens, $option_builder, $notification_builder, $data_builder);

Someone taught me how to fixed it. :)

**Comment by MikeeBulalacao** [comment]
Because I'm putting random characters and not the token itself. That's why it resulted to failure. I'm working with a mobile developer and she's the one sending me the tokens.
