### ISSUE TITLE
The push notification did not send to multiple devices!

### ISSUE THREAD

**Issue by AricMobile** [brozot/Laravel-FCM#109]
I am using "Sending a Downstream Message to Multiple Devices".
I get the device tokens from database and pushed it to array.
$deviceTokens = array();
        foreach ($following as $follow) {
            if (!is_null($follow->user->account->device_token)) {
                array_push($deviceTokens, $follow->user->account->device_token);
            }
        }

Below are the entire source code.

$business_id = $this->deal->business->id;
        $following = Follow::where('business_id', $business_id)->get();
        $deviceTokens = array();
        foreach ($following as $follow) {
            if (!is_null($follow->user->account->device_token)) {
                array_push($deviceTokens, $follow->user->account->device_token);
            }
        }
        $notification = [
            'deal_id' => $this->deal->id,
            'photo' => url('storage/uploads/deals/' . $this->deal->photo),
            'sound' => 'default',
        ];
        $optionBuilder = new OptionsBuilder();
        $optionBuilder->setTimeToLive(60 * 20);

        $notificationBuilder = new PayloadNotificationBuilder('Featured Deal posted');
        $notificationBuilder->setBody($this->deal->description)
            ->setSound('default');

        $dataBuilder = new PayloadDataBuilder();
        $dataBuilder->addData($notification);

        $option = $optionBuilder->build();
        $notification = $notificationBuilder->build();
        $data = $dataBuilder->build();

        foreach ($deviceTokens as $token) {
            $downstreamResponse = FCM::sendTo($token, $option, $notification, $data);
        }

But the push notification did not send multiple devices.
What's wrong? Please help me. 
Thank you in advince!

**Comment by andrelmlins** [comment]
I think I have the same problem.

**Comment by Abnormally** [comment]
Just change
```
foreach ($deviceTokens as $token) {
  $downstreamResponse = FCM::sendTo($token, $option, $notification, $data);
}
```
to
```
$downstreamResponse = FCM::sendTo($deviceTokens, $option, $notification, $data);
```

**Comment by brozot** [comment]
@Abnormally thanks
