### ISSUE TITLE
Is it possible add the notification buttons

### ISSUE THREAD

**Issue by loreberti89** [brozot/Laravel-FCM#11]
Hello, 
first of all congratulations for the excellent work and thanks for share!
I would like ask you (as title says) if it is possible add buttons on notification, for example like "whatsapp" that show if you want reply to message or close notification.

thank you!!

**Comment by brozot** [comment]
Hello thank for your question.

I Think that you should send a notification with a data payload and intercept it in your application in **"onMessageReceived"** (https://firebase.google.com/docs/cloud-messaging/android/receive)

Then construct your notification as you wish
https://developer.android.com/guide/topics/ui/notifiers/notifications.html

Best regards
