### ISSUE TITLE
Just the Notification not the Body Data

### ISSUE THREAD

**Issue by nuga99** [brozot/Laravel-FCM#118]
I want to ask something, I have a json data format and how can I produce the data **onMessageReceived?**
Using Postman I can received both data and notification and when I open the apps it was redirected to the post in the apps, but how can I do from Laravel-FCM? Thanks :)

**Comment by FrancescoBull** [comment]
> I want to ask something, I have a json data format and how can I produce the data **onMessageReceived?**
> Using Postman I can received both data and notification and when I open the apps it was redirected to the post in the apps, but how can I do from Laravel-FCM? Thanks :)

I do not need this either
