### ISSUE TITLE
Send push notification for multiple app.

### ISSUE THREAD

**Issue by mira-thakkar** [brozot/Laravel-FCM#119]
I am using this package for my laravel project and it is working properly for one app. Now i want to integrate api support for multiple apps and that's why want to configure FCM for multiple FCM senders. How can i make it possible ?

**Comment by AbdullahGhanem** [comment]
Have you reached a solution to this problem?

**Comment by AbdullahGhanem** [comment]
i get solution [here](https://github.com/brozot/Laravel-FCM/issues/65#issuecomment-372026290)

**Comment by AbdullahGhanem** [comment]
I get a solution [here](https://github.com/brozot/Laravel-FCM/issues/65#issuecomment-372026290)

**Comment by brozot** [comment]
duplicate #65

**Comment by anuj509** [comment]
I have 2 apps in one project of firebase how can I use same sender id and key to send specific app ? currently it is sending to both the apps.
