### ISSUE TITLE
Sending Click Action

### ISSUE THREAD

**Issue by iqbalprabu14** [brozot/Laravel-FCM#12]
Hi , i have problem.
how to send data click_action from laravel to android ?

**Comment by brozot** [comment]
Hi, 

Normally you can set it in the PayloadNotificationBuilder():

```php
$notification = new PayloadNotificationBuilder(null);
$notification->setClickAction('my_click_action');
```

I hope that will help you

You can find more information on the api references :
https://github.com/brozot/Laravel-FCM/tree/master/doc

Best regards

**Comment by loreberti89** [comment]
Thankyou @brozot !
