### ISSUE TITLE
LaravelFCM \ Response \ Exceptions \ InvalidRequestException (400) to

### ISSUE THREAD

**Issue by AsmaaDev** [brozot/Laravel-FCM#122]
why this accrue when I try to send notification? 

 $notifTitle = '';
        $notifMessage = '';
        $resposData[] = array('mainCode'=> '2', 'subCode' => '4', 'to'=> $invoice->provider->api_token);
        $resposData2[] = array('mainCode'=> '1', 'subCode' => '2');

        $devicesTokens = UserDevice::where('user_id',  $invoice->provider_id)->select('device_token', 'device_type')->get();

        $devicesAndroidTokens = [];
        $devicesIosTokens = [];
        //
        if ($devicesTokens) {
                
            foreach($devicesTokens as $token) {

                if($token->device_type == 'android'){

                    $devicesAndroidTokens[] = $token->device_token;
                }
                else{
                    $devicesIosTokens[] = $token->device_token;

                }
            }
//  dd($devicesIosTokens);
            sendMultiNotificationIos($notifTitle, $devicesIosTokens , $resposData);
            sendMultiNotificationOperation($notifTitle, $devicesAndroidTokens , $resposData);
            
            sendMultiNotification('New Activity', 'user reject the invoice' ,$devicesIosTokens , $resposData2);
            sendMultiNotification('New Activity', 'user reject the invoice' ,$devicesAndroidTokens , $resposData2);

            saveNotification($invoice->provider_id, 'New Activity', '4', 'user reject the invoice');
        }
      

 what is the wrong here ?

function sendMultiNotification($notificationTitle, $notificationBody, $devicesTokens) {

    $optionBuilder = new OptionsBuilder();
    $optionBuilder->setTimeToLive(60*20);

    $notificationBuilder = new PayloadNotificationBuilder($notificationTitle);
    $notificationBuilder->setBody($notificationBody)
        ->setSound('default');

    $dataBuilder = new PayloadDataBuilder();
    $dataBuilder->addData(['a_data' => 'my_data']);

    $option = $optionBuilder->build();
    $notification = $notificationBuilder->build();
    $data = $dataBuilder->build();

    // You must change it to get your tokens
    $tokens = $devicesTokens;

    $downstreamResponse = FCM::sendTo($tokens, $option, $notification, $data);

    $downstreamResponse->numberSuccess();
    $downstreamResponse->numberFailure();
    $downstreamResponse->numberModification();

    //return Array - you must remove all this tokens in your database
    $downstreamResponse->tokensToDelete();

    //return Array (key : oldToken, value : new token - you must change the token in your database )
    $downstreamResponse->tokensToModify();

    //return Array - you should try to resend the message to the tokens in the array
    $downstreamResponse->tokensToRetry();

    // return Array (key:token, value:errror) - in production you should remove from your database the tokens present in this array
    $downstreamResponse->tokensWithError();

    return ['success' => $downstreamResponse->numberSuccess(), 'fail' => $downstreamResponse->numberFailure()];
}
function sendMultiNotificationIos($notificationTitle, $devicesTokens, $resposData)
{
    $optionBuilder = new OptionsBuilder();
    $optionBuilder->setTimeToLive(60 * 20);

    $notificationBuilder = new PayloadNotificationBuilder($notificationTitle);
    
    $dataBuilder = new PayloadDataBuilder();
    $dataBuilder->addData($resposData[0]);
    
    $option = $optionBuilder->build();
    $notification = $notificationBuilder->build();
    $data = $dataBuilder->build();

    // You must change it to get your tokens
    $tokens = $devicesTokens;

    $downstreamResponse = FCM::sendTo($tokens, $option, null, $data);

    $downstreamResponse->numberSuccess();
    $downstreamResponse->numberFailure();
    $downstreamResponse->numberModification();

    //return Array - you must remove all this tokens in your database
    $downstreamResponse->tokensToDelete();

    //return Array (key : oldToken, value : new token - you must change the token in your database )
    $downstreamResponse->tokensToModify();

    //return Array - you should try to resend the message to the tokens in the array
    $downstreamResponse->tokensToRetry();

    // return Array (key:token, value:errror) - in production you should remove from your database the tokens present in this array
    $downstreamResponse->tokensWithError();

    return ['success' => $downstreamResponse->numberSuccess(), 'fail' => $downstreamResponse->numberFailure()];
}

**Comment by codeurfou** [comment]
Hello, same pb here

**Comment by codeurfou** [comment]
@AsmaaDev Check if your APN certificate for ios is still valid.

**Comment by brozot** [comment]
An other issue has been opened, I think there are an issue with the json here.

I will close your issue and keep this one opened #132
