### ISSUE TITLE
Dynamic badge sending to Multiple Devices

### ISSUE THREAD

**Issue by normeno** [brozot/Laravel-FCM#126]
I'm trying to use https://github.com/brozot/Laravel-FCM#sending-a-downstream-message-to-multiple-devices, using this option, how can I send different badge numbers for different tokens? it's possible?

**Comment by brozot** [comment]
Hi, sorry for the long delay between the question and any response. 
AFAIK you have to send the same payload if you want to send notification to multiple devices at once.
