### ISSUE TITLE
Send image in notification content

### ISSUE THREAD

**Issue by kezern** [brozot/Laravel-FCM#127]
Hi,
I'm sending notifications correctly, but I whould like to know how can I send an image with the notification?

**Comment by Xoshbin** [comment]
You have to use data messages, https://github.com/brozot/Laravel-FCM#data-messages
then in your Android application you have to receive the image url and show it `.setLargeIcon(myBitmap)`

**Comment by brozot** [comment]
@Xoshbin thanks
