### ISSUE TITLE
How to get Device Tokens or userId to send notification?

### ISSUE THREAD

**Issue by rashedshaon** [brozot/Laravel-FCM#129]
I see on documentation given an example to send multi notification by tokens,
`$tokens = MYDATABASE::pluck('fcm_token')->toArray();`
But I can not understand how I will get tokens from firebase database. What actually mean **MYDATABASE**  
class and where I found it.
Please give me the procedure or what I have to do?

**Comment by Xoshbin** [comment]
You have to collect the ID of the devices by yourself and then you can send the notification. this link describes how to retrieve the ID of the clients.
https://firebase.google.com/docs/cloud-messaging/android/client#sample-register

https://github.com/brozot/Laravel-FCM/issues/140

**Comment by brozot** [comment]
thanks @Xoshbin
