### ISSUE TITLE
Where is the sender ID located?

### ISSUE THREAD

**Issue by apoorvpal01** [brozot/Laravel-FCM#140]
Hey

 I am new to this. I couldn't find my sender ID in the config. Where is it or is it to be entered by me? If so where? I am asking this because if I send a payload from postman, I always get SenderMismatch.

**Comment by Xoshbin** [comment]
You have to collect the ID of the devices by yourself and then you can send the notification. this link describes how to retrieve the ID of the clients.
https://firebase.google.com/docs/cloud-messaging/android/client#sample-register

**Comment by lAndresul** [comment]
On the firebase console, project settings "Cloud Messaging" Tab

**Comment by brozot** [comment]
@Xoshbin  and @lAndresul Thanks
