### ISSUE TITLE
Dynamically configured FCM_SERVER_KEY and FCM_SENDER_ID

### ISSUE THREAD

**Issue by adamulator** [brozot/Laravel-FCM#145]
Hello,
I have so far used this package successfully to send push notifications in my Firebase project, however now I would like to start using this package with 2 firebase projects. Is it possible to set FCM_SERVER_KEY and FCM_SENDER_ID on per-notification basis? Thank you.

**Comment by menkaff** [comment]
@adamulator  How did you handle different configuration?

**Comment by ElijahGM** [comment]
How did you handle this

**Comment by ElijahGM** [comment]
> How did you handle this

```
app()->instance("fcm.sender", null);
app('config')->set('fcm.http.server_key', NEW_KEY));
app('config')->set('fcm.http.sender_id',  NEW_ID));
```

this seems to work
