### ISSUE TITLE
Class fcm.sender does not exist

### ISSUE THREAD

**Issue by bearn666** [brozot/Laravel-FCM#15]
when i call:
`$downstreamResponse = FCM::sendTo($this->tokens, $this->options, $this->notification,$this->data);`

can someone help?

**Comment by brozot** [comment]
Hi, 

I think that you have forgotten to add the `FCMServiceProvider` in the file `config/app.php` for laravel or `boostrap/app.php` for lumen.

you can find more information  in the installation section of the readme https://github.com/brozot/Laravel-FCM.

Can you give me a feedback if this solution solve your issue or not.

Best 

Nicolas

**Comment by aliuwahab21** [comment]
Please am facing the same error even though I have added         LaravelFCM\FCMServiceProvider::class to the config/app.php.

**Comment by Punith1234** [comment]
Hey @aliuwahab21 did you try --

composer dumpautoload
php artisan config:cache
php artisan optimize

**Comment by amalkronz** [comment]
I try what you said but nothing work well, any suggestion please?!
