### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by kundaneyug** [brozot/Laravel-FCM#152]
Having issues with string helper functions

**Comment by HasanAlyazidi** [comment]
Any updates about Laravel 6?

**Comment by i-am-dominic-arendse** [comment]
Would it be possible to have a separate branch in addition to master to support the ongoing changes to Laravel 6? Possibly a dev branch or unstable branch?

**Comment by umairali** [comment]
Please add the laravel 6 support. i am trying to install but its showing below error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install brozot/laravel-fcm v1.2.6
    - Conclusion: don't install brozot/laravel-fcm v1.2.5
    - Conclusion: don't install brozot/laravel-fcm v1.2.4
    - Conclusion: don't install brozot/laravel-fcm v1.2.3
    - Conclusion: don't install brozot/laravel-fcm v1.2.2
    - Conclusion: don't install brozot/laravel-fcm v1.2.1
    - Conclusion: remove monolog/monolog 2.0.0
    - Installation request for laravel/framework (locked at v6.0.3, required as ^6.0) -> satisfiable by laravel/framework[v6.0.3].
    - Installation request for brozot/laravel-fcm ^1.2 -> satisfiable by brozot/laravel-fcm[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6].
    - Conclusion: don't install monolog/monolog 2.0.0
    - brozot/laravel-fcm v1.2.0 requires monolog/monolog ^1.19 -> satisfiable by monolog/monolog[1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.25.0, 1.25.1, 1.x-dev].
    - Can only install one of: monolog/monolog[1.19.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.20.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.21.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.22.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.22.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.23.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.24.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.0, 2.0.0].
    - Can only install one of: monolog/monolog[1.25.1, 2.0.0].
    - Can only install one of: monolog/monolog[1.x-dev, 2.0.0].
    - Installation request for monolog/monolog (locked at 2.0.0) -> satisfiable by monolog/monolog[2.0.0].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by NikaQ** [comment]
Please add Support for Laravel 6

**Comment by sherifalaa55** [comment]
+1

**Comment by brainlet-ali** [comment]
+1

**Comment by alisanalacam** [comment]
+1

**Comment by el3zahaby** [comment]
+1 !

**Comment by Allyans3** [comment]
+1

**Comment by Yethroy** [comment]
+1

**Comment by iamriajul** [comment]
+1

**Comment by gulshan11315** [comment]
+1

**Comment by ahmedzahran** [comment]
+1

**Comment by drashoor** [comment]
+1

**Comment by anhtt57** [comment]
If you have gone through the upgrade guide then you must know that

String and Array
Helpers are removed from Core Framework
So if if You need to still use the helper install the package

`composer require laravel/helpers`

and all the helpers are moved to this package

**Comment by bassem-shoukry** [comment]
+1

**Comment by vigneshgurusamy** [comment]
> If you have gone through the upgrade guide then you must know that
> 
> String and Array
> Helpers are removed from Core Framework
> So if if You need to still use the helper install the package
> 
> `composer require laravel/helpers`
> 
> and all the helpers are moved to this package

@anhtt57 Still, you can't upgrade to Laravel 6.x. First package dependency should be updated to work with Laravel 6.x.

```json
"illuminate/support": "5.*|^6.0"
```

**Comment by brozot** [comment]
Hi all, 
A new version has been release, this version should bring the support of Laravel 6
https://github.com/brozot/Laravel-FCM/releases/tag/1.3.0

**Comment by richardkeep** [comment]
Hi @brozot I am still experiencing the monolog issue with v1.3.0
![Capture](https://user-images.githubusercontent.com/3874381/69611421-c6f23400-103e-11ea-8d9d-5c433f68852c.JPG)

**Comment by Yethroy** [comment]
+1

**Comment by brozot** [comment]
It seems that the version of monolog used by laravel-fcm is more strict that the one used by [laravel 6](https://github.com/laravel/framework/blob/6.x/composer.json)`"monolog/monolog": "^1.12|^2.0",` I will try to make the package compatible with version of monolog 1.12 and 2.0" that should solve this issue

**Comment by brozot** [comment]
Hi @richardkeep, 

I have updated the composer file: Could you please try with `"brozot/laravel-fcm": "dev-master "` if it solves the problem, I will create a version 1.3.1

**Comment by richardkeep** [comment]
> Hi @richardkeep,
> 
> I have updated the composer file: Could you please try with `"brozot/laravel-fcm": "dev-master "` if it solves the problem, I will create a version 1.3.1

The issue has been resolved. Tested with Laravel 6.6.0

**Comment by brozot** [comment]
Thanks @richardkeep
