### ISSUE TITLE
Multicast limit ?

### ISSUE THREAD

**Issue by yoannsark** [brozot/Laravel-FCM#158]
Hello,

Is there a limit of tokens for sending messages to multiple devices ?

Is it 100 like the Firebase Admin SDK ?

> You can specify up to 100 device registration tokens per invocation.

[https://firebase.google.com/docs/cloud-messaging/send-message?authuser=0#send_messages_to_multiple_devices](url)

**Comment by brozot** [comment]
Hi the token are split by the package and are sent by group of 100
```     
$partialTokens = array_chunk($to, self::MAX_TOKEN_PER_REQUEST, false);
            foreach ($partialTokens as $tokens) {
                $request = new Request($tokens, $options, $notification, $data);
```
