### ISSUE TITLE
How to send multiline notifications?

### ISSUE THREAD

**Issue by carlosjac** [brozot/Laravel-FCM#16]

**Comment by brozot** [comment]
Hi,

Notification messages can be only used to send simple notification, if you want to send a custom notification ( multiline or special actions) just send a data message to your app. In your application code, intercept it in the method onMessageReceived then construct your custom notification like explaining on the android documentation.
https://developer.android.com/guide/topics/ui/notifiers/notifications.html

Maybe this closed issue can help you for sending message data #13

Please let me know if my answer has helped you

Best Regards,

Nicolas
