### ISSUE TITLE
How to change icon notification?

### ISSUE THREAD

**Issue by carlosjac** [brozot/Laravel-FCM#17]

**Comment by brozot** [comment]
Hi,

The package offers a setIcon method to the PayloadNotificationBuilder;

Below a small example how to use it

```php
$optionBuiler = new OptionsBuilder();

$notificationBuilder = new PayloadNotificationBuilder();
$notificationBuilder->setIcon("the same name that the icon in my drawable directory");

FCM::sendTo($token, $option->build(), $notificationBuilder->build(), null);
```
This solution works for notification message. If message is intercepted in the method onMessageReceived you must create your notification with Notification.Builder() in Android and set the icon here.

Please let me know if my answer has helped you

Best regards,

Nicolas

**Comment by jonajgs** [comment]
Hi @brozot I have a question about the icon, when the app is open, the notification if show me the icon, but when the app is close, the icon notification is in blank icon, Where must be my icon notification to I can solvethis problem ?

thanks :)
