### ISSUE TITLE
What kind of token is required?

### ISSUE THREAD

**Issue by aungpyaekyaw** [brozot/Laravel-FCM#170]
$token = "a_registration_from_your_database";

I'm not clear what kind of token is needed to provide.

**Comment by dennis1804** [comment]
That token is a FCM_token (Firebase Cloud Messaging)

**Comment by aungpyaekyaw** [comment]
> That token is a FCM_token (Firebase Cloud Messaging)

How can I acquired this token in my project. Is this token specified for each user and how can I generate token for each user? and do users have to register with google to get this token?

**Comment by dennis1804** [comment]
you need to have a javascript or app running on the front-end that can process the users request to receive notifications. that will generate a FCM_token which you need to push to the laravel application.
please take a look at the FCM documentation. they also have some examples which you can use for your front-end.
https://firebase.google.com/docs/cloud-messaging/js/client
then just use ajax / XMLhttp to push the token to the laravel database and you can send notifications.
https://github.com/firebase/quickstart-js/tree/master/messaging

**Comment by aungpyaekyaw** [comment]
Thank for your reply @dennis1804 . It's very helpful and I will look into docs that you mentioned.
