### ISSUE TITLE
Does not install in Laravel 4

### ISSUE THREAD

**Issue by adarshchacko** [brozot/Laravel-FCM#2]
I tried to install Laravel-FCM but was unable to do so.

Here is what I did:

1. I included     "brozot/laravel-fcm": "^0.9.3"     in the require array of composer.json but it refuses to install. It returns an error message which tells me that I need to update my guzzle to ~6.0.

![cms](https://cloud.githubusercontent.com/assets/8156026/16725741/4cc0da72-4776-11e6-8dcc-eda29d09cc8a.JPG)

2. I tried replacing my current guzzle to ~6.0 which in turn tells me that I need to update my laravel  framework.

Is there a way or a work around to make it work in laravel 4.2.

**Comment by brozot** [comment]
Hello thanks for your interest in this package.

I'm sorry but this package is constructed to work with Laravel > 5.
Unfortunately it can't work with Laravel 4.2 simply.

I will note this constraint in the documentation.
