### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by c13andka** [brozot/Laravel-FCM#25]
Hello i am using your plugin but it does not send a push notificiation for me, is there something wrong with these lines of code? 

   $notificationBuilder = new PayloadNotificationBuilder('my title');
   $notificationBuilder->setBody('body')		
		                  ->setSound('default');			
   
$notification = $notificationBuilder->build();

$optionBuilder = new OptionsBuilder();

$deviceResponse = FCM::sendTo($userKey, $optionBuilder->build(), $notification);

**Comment by brozot** [comment]
Hello

It looks ok, are you sure about your client implementation ? 
Your token is valid ? 
your key is valid ?

Best regards,
