### ISSUE TITLE
Type error: Too few arguments to function Illuminate\\Support\\Manager::createDriver()

### ISSUE THREAD

**Issue by theunreal** [brozot/Laravel-FCM#29]
I installed the package in my laravel, and when I'm trying to send a push notification to my device using the exact same code in the readme, I get the following error:

`Type error: Too few arguments to function Illuminate\\Support\\Manager::createDriver(), 0 passed in \/home\/pokemoti\/public_html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Manager.php on line 87 and exactly 1 expected`

The line caused the error is:

`$downstreamResponse = FCM::sendTo($token, $option, $notification, $data);`

I couldn't figure out what's wrong as soon as it's the documentation code..

What's could have gone wrong?

**Comment by mohamedsharaf** [comment]
@theunreal how u solved this?

**Comment by MilosR** [comment]
For anyone who got same issue try to publish config file using `php artisan vendor:publish`

**Comment by saintsweeto** [comment]
Anyone solved this?

**Comment by olesla** [comment]
I had this problem. It was caused by a missing return on the bottom of my config file.
