### ISSUE TITLE
How can i add icon ?!!!

### ISSUE THREAD

**Issue by Enemy22** [brozot/Laravel-FCM#30]
Hi, how can we add an icon to notification ?!!

**Comment by jonajgs** [comment]
I had the same problem, to resolve this, in your `NotificationBuilder` set the icon

```
$notificationBuilder->setBody($body)
	->setIcon('ic_card_travel_black_24dp')
        ->setSound('default');
```

where   
setIcon is the drawable icon.  
for example, you can download any icon from [this](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html), and copy all drawable folder in main/res, the string of the setIcon is the name of the icon.  
 I hope I've helped.

**Comment by keanhaur** [comment]
It still using my default app icon even I have add the new icon in to the main/res.
