### ISSUE TITLE
Sending a Downstream Message to a Device

### ISSUE THREAD

**Issue by karim-abdelmegeed** [brozot/Laravel-FCM#33]
i have an error 

cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
 i tried to add file cacert.pem in php.ini but error  remains
help please

**Comment by brozot** [comment]
I think the issue is due to guzzle used by this package, maybe this thread could help you : http://stackoverflow.com/questions/24923604/guzzle-curl-error-60-ssl-unable-to-get-local-issuer

Best regards

**Comment by brozot** [comment]
Some issue was solved at the end of this thread
Duplicate of #43
