### ISSUE TITLE
What is this 'registration_from_your_database' meaning?

### ISSUE THREAD

**Issue by awebr000** [brozot/Laravel-FCM#34]
In this example i see this part, but i don't know how to replace this line:

```php

$token = "a_registration_from_your_database";

```

I don't know how to get the token, can you give explanation.

**Comment by jonajgs** [comment]
when you register a token in a real device in this function

```
onRegister: function(data) {
    //save in database data.token
}
```

**Comment by awebr000** [comment]
Got it!
