### ISSUE TITLE
Missing argument 1

### ISSUE THREAD

**Issue by naran3434** [brozot/Laravel-FCM#35]
`ErrorException in Manager.php line 77:
Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /var/www/html/API-DIR/events/vendor/illuminate/support/Manager.php on line 87 and defined`

When i try to send notification i service above mentioned error. i am using lumen framework.

Here is my code : 

`$optionBuiler = new OptionsBuilder();
        $optionBuiler->setTimeToLive(60*20);

        $notificationBuilder = new PayloadNotificationBuilder('My test notification');
        $notificationBuilder->setBody('Hello world')
                             ->setSound('default');

        $dataBuilder = new PayloadDataBuilder();
        $dataBuilder->addData(['a_data' => 'my_data']);

        $option = $optionBuiler->build();
        $notification = $notificationBuilder->build();
        $data = $dataBuilder->build();

        $token = "token";

       $downstreamResponse = FCM::sendTo($token, $option, $notification, $data);`

Thanks

**Comment by kasparrov** [comment]
1) add provider and aliases
2) ./artisan vendor:publish
3) add keys ti .env file or to fcm.php in config directory

**Comment by naran3434** [comment]
Thanks for reply.
And Sorry I forgot to close issue. since I fixed it as soon as I posted issue here.
Add fcm.php to fix it.
