### ISSUE TITLE
How get my id´s token devices

### ISSUE THREAD

**Issue by helderalvesoliveira** [brozot/Laravel-FCM#37]
Hello, i´m newer and hi have a question:
How can i get my tokens id´s phone ? ( $tokens = MYDATABASE::pluck('fcm_token')->toArray(); )
Thanks very much.

**Comment by brozot** [comment]
Hello, I am not sure to understand your question but I am going to try to answer.

You have the responsibility to manage your tokens by yourself.

Firebase provide to you a sdk to implement  in your mobile app. This sdk is given to you a token for each of your devices. You have to register these tokens in your Laravel Application.Then you can fetch tokens from your db with Eloquent. 

You need to provide an array of tokens to this package.

Let me know if this response is helping you or if you need more help.

Best regards

Nicolas

**Comment by helderalvesoliveira** [comment]
Hello, your answer is what i whant ... :-) thanks very much!
