### ISSUE TITLE
Missing Namespace for Topics in documentation (minor)

### ISSUE THREAD

**Issue by ANich** [brozot/Laravel-FCM#38]
Hey @brozot Great library, got some great use from it.

I just noticed that the namespace for `Topics` wasn't included in the documentation. Shouldn't be difficult to add `use LaravelFCM\Message\Topics;` to the "Topics Messages" section of the documentation to make it immediately obvious to users. I can open a PR if you'd like.

Thanks again 👍

**Comment by brozot** [comment]
Hello thank you for your interest for this package and for your contribution. you can make a PR and i will accept it quickly

**Comment by ANich** [comment]
Alright, will do 👍
