### ISSUE TITLE
Consuming too much memory and CPU resources when sending push to large number of users

### ISSUE THREAD

**Issue by tahirwaseer** [brozot/Laravel-FCM#41]
I am trying to send push notifications in bulk. Now I've 400 devices registered on my live server. When we are sending a push notification to all of them our memory and CPU usage rises drastically thus slowing down our system. When I check with the server logs 400-500 new processes are being generated when push notification is triggered. I am using the same code from package readme example i.e 
`$tokens = array of push tokens;
 $downstreamResponse = FCM::sendTo($tokens, $option, $notification, $additionalData);  

 if ($downstreamResponse->tokensToDelete()) {
      Device::whereIn('device_push_token',$downstreamResponse->tokensToDelete())->delete();
}
`
Is there anything I am doing wrong? Or there are any limitations from FCM/this package? Or should I try any alternate method like groups, topics?

**Comment by brozot** [comment]
Hi, The package should work well for this amount of token. Group and Topics is a different usage. I will take a look. Thank you very much

**Comment by tahirwaseer** [comment]
@brozot thanks for responding. I really don't have logs for threads and all that I got this information from support guy. He was synced with me when this process was going to trigger. But I do have some usage screen shots may be they can clarify how much impact it had on the system. 
Before and after usage: 
<img width="873" alt="normal usage" src="https://cloud.githubusercontent.com/assets/9745802/25010488/b75dcaf2-2083-11e7-89f4-28051d64c4fb.png">

When push was being sent;
<img width="833" alt="when sending push" src="https://cloud.githubusercontent.com/assets/9745802/25010510/ca526a82-2083-11e7-9fa1-afcc83b44558.png">

And this thing caused a huge slow down on our APIs and as well on our cPanel.

**Comment by tahirwaseer** [comment]
@brozot anything on this issue?? Or can you suggest me any alternate implementation?

**Comment by brozot** [comment]
It's quite strange because the package should have send only one http request to FCM.

Maybe you can check that you make only one call (storage/logs/laravel-fcm).

All your tokens are valid ? 
There are a loop in the response if there are a failure. But i will be surprised if this loop has a bad influence with your server, maybe can you log a timestamp before and after it.

**Comment by brozot** [comment]
@tahirwaseer Have you find something wrong ?

**Comment by tahirwaseer** [comment]
@brozot I've been looking into your code and it seemed to be written correctly and doing fine by sending a single request in chunks. But because it is a sync. call and it was making system pretty slow during the process so another option for me was to move this task to a background process. As this package doesn't work out of the box with Laravel Jobs/Queues as mentioned [here](https://github.com/brozot/Laravel-FCM/issues/14) so I've to come up with some other way around. I ended up writing my own code to communicate with FCM servers and moved that to a background job, that seemed to be working pretty good and also not stopping the normal flow of application. Although it is taking almost same amount of resources  as your code does, so still thumbs up to your work and it really helped me getting around this situation.

**Comment by brozot** [comment]
Ok thank you very much for your investigations. I'm currently working on a queue implementation. It should be available soon

Best Regards

**Comment by prasanthsd** [comment]
Any idea of a time frame for the queue implementation?

Also would be great if you could have a notification channel implementation ( Similar to https://github.com/benwilkins/laravel-fcm-notification ). I could send a pull request and get this working if you already have the queue implementation somewhere. Please let me know
