### ISSUE TITLE
How can I make phone vibrate when push is send

### ISSUE THREAD

**Issue by harmanpreet27** [brozot/Laravel-FCM#44]
Push notification working fine but the phone which receives push notification does not vibrate. Vibration is on and I can see vibration with other apps. Is there any way we can send vibration command through this package.

**Comment by brozot** [comment]
Hello, 

Notification message is handle and shown by Android and there are no key for vibration.
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

If you want to decide how notifications are displayed in your phone. you can make a data message. In your application you can handle data message with onMessageReceived method (see firebase documentation).

https://firebase.google.com/docs/cloud-messaging/android/receive

Data message can be send with this package using PayloadDataBuilder

```php
$dataBuilder = new PayloadDataBuilder();
$dataBuilder->addData(['a_data' => 'my_data']);

$data = $dataBuilder->build();

$token = "a_registration_from_your_database";

$downstreamResponse = FCM::sendTo($token, null, null, $data);```

Best Regards
