### ISSUE TITLE
Class fcm.sender does not exist

### ISSUE THREAD

**Issue by milindrc** [brozot/Laravel-FCM#46]
followed the instructions strictly still the error exists while using FCM::sendTo

**Comment by brozot** [comment]
Helle milindrc, 

Have you do this command ? `php artisan vendor:publish`

**Comment by singhkishan93** [comment]
Hi brozot, I did php artisan vendor:publish, but no luck.
I am gitting following error 
ReflectionException (-1)
Class fcm.sender does not exist
can you please help?
