### ISSUE TITLE
Ios not receiving notifications

### ISSUE THREAD

**Issue by ShVitaliy** [brozot/Laravel-FCM#49]
Working fine with android, but doesn't work with ios. Tried set priority to high and content_available to true. No effect. In the same time, it works fine when I'm sending notification via firebase console or curl (both from php or linux console). Can you help me? Is it bug or I'm doing smth wrong? I tried the example from documentation (downstream Messages)

**Comment by ShVitaliy** [comment]
Sorry it was my fault, mistake in logic. Library works fine both in android and ios

**Comment by Abdulhmid** [comment]
can you share your code send push notif to IOS platform,
i have follow instruction from documentation, and after i log, my push Notif is succes, but on my IOS developer say not received Push Notif has i'm send, 
thanks before

**Comment by keyurgwebplanex** [comment]
I faced the same problem.
Can you please tell me how to send notifications in IOS?

**Comment by ShVitaliy** [comment]
unfortunatly, i haven't the source code of that project already. but, as i told before, the code was the same, as for android.

if you faced with troubles, you can easily send messages via curl, or write your own wrapper around it.
if you didn't tried yet, the simpliest curl code example is so:

`
            $url = 'https://fcm.googleapis.com/fcm/send';
  
                $fields = [
                'registration_ids' => [
                    $this->push_token
                ],
                'notification' => ['body' => $message, 'title' => $title, 'sound' => $sound, 'badge' => $badge],
                'priority' => 10
            ];
            $fields = json_encode ( $fields );
            $headers = [
                'Authorization: key=' . env('PUSH_TOKEN'),
                'Content-Type: application/json'
            ];

            $ch = curl_init();
            curl_setopt( $ch, CURLOPT_URL, $url );
            curl_setopt( $ch, CURLOPT_POST, true );
            curl_setopt( $ch, CURLOPT_HTTPHEADER, $headers );
            curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
            curl_setopt( $ch, CURLOPT_POSTFIELDS, $fields );

            $out = curl_exec( $ch );
            curl_close( $ch );
            Log::info('FCM answer: ' . $out);
`
library examples you can find in documentation. Hope, it will help

**Comment by tamirkonor** [comment]
Is the library working for ios >11 
the server is using the library and push arrives on Android, not on ios when sending from the fcm console the push arrives. 
the apps are in ionic but again it is received when sent from the fcm console.
