### ISSUE TITLE
How to add optional payload into a notification?

### ISSUE THREAD

**Issue by chimit** [brozot/Laravel-FCM#63]
`PayloadNotificationBuilder` doesn't have `addData` method. So how to add custom key-value pairs into a push notification?

**Comment by ronanversendaal** [comment]
The `addData` method is available through the `PayloadDataBuilder` class. 
The `PayloadNotificationBuilder` handles the title, body, icon and such.

**Comment by chimit** [comment]
I would like to use standard APNS notifications which can be delivered when the app is in the background. If I'm not mistaken Data messages don't cover my needs.
I had to switch to pure Firebase API. It's not so hard.

**Comment by nirmalgoswami** [comment]
so still not solution with this library ?

[my problem](https://stackoverflow.com/questions/37711082/how-to-handle-notification-when-app-in-background-in-firebase/42279260#42279260) - payload is not receiving when app is in background
