### ISSUE TITLE
When does tokensToModify get populated?

### ISSUE THREAD

**Issue by ronanversendaal** [brozot/Laravel-FCM#64]
I've been implementing your package to send FCM notifications, which is working fine. Currently I'm implementing a case for tokensToModify.

By reinstalling my client-app, I am able to generate or refresh tokens. At this moment though the old token is still in my database. 

So when sending to the old token, ( after refreshing tokens from the client ), I expect to see the old token as key with the new token as value in the tokensToModify() array. This never happens though. The old tokens will always be inserted in to the tokensToDelete array. 

I might have misunderstood the tokensToModify method.  But i would like some explanation on how to use this method on the server side.

**Comment by ronanversendaal** [comment]
Hi there, I would still like to know more about this. *gentle bump*

**Comment by brozot** [comment]
Hi,

Sorry to answer only now. 

When your are uninstalling you app the device is unregistered on FCM. That's mean that you token is not updated but revoked and recreated for a new instance ID. 

tokensToModify is only used rarely when FCM rotate token. (I don't know any way to simulate that).

If your app is uninstalled your are responsable to resend and save the new token on your server.

I hope that this response helps you

Best Regards
