### ISSUE TITLE
Showing error "error setting certificate verify locations:"

### ISSUE THREAD

**Issue by ascuet** [brozot/Laravel-FCM#70]
I am using this package and here is the below line:
`$downstreamResponse = FCM::sendTo($token, $option, $notification, $data);`

But shows error as below:
`
(1/1) RequestExceptioncURL error 77: error setting certificate verify locations:

CAfile: [pathtothisfile]\cacert.pem

CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
`

I changed php.ini (xampp) as below:
`D:\xampp\php\cacert.pem`

Also, placed the file in php folder accordingly. But still showing error.

How can I solve this problem?

**Comment by brozot** [comment]
Hi ascuet 

Some people had issues with certificates, maybe theses thread can help you: 

https://github.com/brozot/Laravel-FCM/issues/43
https://github.com/brozot/Laravel-FCM/issues/33

Let me know if it's help you

Best Regards,

Nicolas
