### ISSUE TITLE
Sending a Notification to all the registered devices

### ISSUE THREAD

**Issue by Fawzanm** [brozot/Laravel-FCM#73]
I have the same request as this [issue](https://github.com/brozot/Laravel-FCM/issues/1) 

Is it possible to send a notification to all the registered users without passing an array of tokens? Because Firebase console allows us to do it using Target: 'User Segment' where we can simply send a notification to all the users without specifying the tokens.

**Comment by brozot** [comment]
Hi, 

Unfortunately it's not allowed by FCM

Here an extract of the official documentation :

Note that some fields in the Notifications composer are not available through the FCM server protocols. For example, you can target user segments based on app, app version, language or user properties in ways that are not available using the field in the server API.

https://firebase.google.com/docs/cloud-messaging/send-with-console

Best regards, 

Nicolas
