### ISSUE TITLE
Click action

### ISSUE THREAD

**Issue by mustafaabduljalil** [brozot/Laravel-FCM#75]
Is there is click action option ???
if there is how can i set it ?

thanks

**Comment by brozot** [comment]
Hello, 

You can set click action like that: 

```php
$notificationBuilder = new PayloadNotificationBuilder();
$notificationBuilder
    ->setClickAction("action_name");
```

On **Android** you can handle it for example with this code 
```xml
<activity android:name=".ActionClicked">
     <intent-filter>
          <action android:name="action_clicked" />
          <category android:name="android.intent.category.DEFAULT" />
     </intent-filter>
</activity>
```

On **ios** click_action => category. It's a little bit more complexe. You can find more information on the official [documentation.](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SupportingNotificationsinYourApp.html#//apple_ref/doc/uid/TP40008194-CH4-SW26)

On **javascript** you must set an url (must be https)

```php
$notificationBuilder = new PayloadNotificationBuilder();
$notificationBuilder
    ->setClickAction("https://google.com");
```

Best Regards, 

Nicolas

**Comment by MuhammadTalhaAfzal** [comment]
@brozot How can i use setClickAction() on ionic 2 framework for push notification?

**Comment by YsightTechie** [comment]
The click_action works great except if you are running an application that performs as an app on the mobile phones (ios, android) and browsers.  I have an app that runs on all three.  It is a command and control application that customers can use on their phones or on their laptop/desktop.  I send a notification and data in the message and thus must set the click_action for the android intent which is not the url I need in the browser.  Thus, the android version works but the browser version does not.  Would you please add another way for the Android to open the intent and not use the click action?  It seems to me to be a bit of a hack to use a click_action for an intent.  Why not call it an "intent" making if very clear.  This product you all have created is fantastic!  Such a change would really help this developer and I am certain many others especially in clarity of purpose of these fields.  Thank you.

**Comment by yasirmehmood123** [comment]
@brozot 
->setClickAction("https://google.com");
this is not working if i click on push notification it do not redirects any where stays on the same page
