### ISSUE TITLE
Grouping notifications like whatsapp

### ISSUE THREAD

**Issue by carvemerson** [brozot/Laravel-FCM#77]
Is it possible to group messages like whatsapp app?
If yes, how can I do it with FCM?

**Comment by brozot** [comment]
Hello,

# Android 
There are 2 possibilities to group notifications

* Using tag `$notificationbuilder->setTag('my tag')`
* Using data message (in your app handle function `onMesageReceived()` and create notification from the code with "NotificationManager”)

# iOS
There is no way to group notification with FCM.
In APNs, you can set a thread-id parameter, but it's not currently supported on FCM.

Best regards, 

Nicolas

**Comment by carvemerson** [comment]
The `tag` override the last message. It is good, but I need something like this:

![screenshot_2015-02-01-19-40-04](https://user-images.githubusercontent.com/6718864/29724831-7dd20f2e-89a0-11e7-8a83-0aaa11999192.png)

Is it possible with message from the server?

**Comment by brozot** [comment]
Hello, I think that you can do that using a dataPayload. 

```php
$dataBuilder->addData([
    'data' => 'my_data_1',
    'data2' => 'my_data_2'
];

$downstreamResponse = FCM::sendTo($tokens, null, null, $dataBuilder->build());
```

Then when onReceived is fired, create your notification like explain in this thread
http://www.androidgig.com/inbox-style-notification-like-whatsapp/

Best regards,

**Comment by carvemerson** [comment]
Ok, Thanks!!

**Comment by IamSagar** [comment]
If You will get Notification one by one and only have one data payload.
In this case can you update current notification like Whats App?
