### ISSUE TITLE
Undefined variable: response

### ISSUE THREAD

**Issue by sujit223** [brozot/Laravel-FCM#8]
what is the variable **response** passed to "new DownstreamResponse" under Downstream Messages example. I am getting an error with this.

**Comment by brozot** [comment]
Hi,

Thank's for this remarks, there are indeed a mistake in this example, I will remove the following line in the example : 
`$downstreamResponse = new DownstreamResponse($response, $tokens);`

You can remove it now in your code.

Best regards

**Comment by sujit223** [comment]
Thanks really appreciate your help and an awesome package it is.
