### ISSUE TITLE
Class 'FCM' not found

### ISSUE THREAD

**Issue by loranger** [brozot/Laravel-FCM#81]
Hello,

Everything works flawlessly while running inside laravel app, but as soon as I try to send a push from an artisan command, I get the following exception :

```shell
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'FCM' not found
```

Of course FCMProvider is defined inside my `config/app.php` file, and the aliases too

Did I miss something ?

**Comment by loranger** [comment]
A simple `composer dump` fixed the issue

**Comment by primangesta** [comment]
Hello,

I need help for this same issue, everything works and i can send notification to my phone in my local.
But after upload to server i got this issue. i don't know why
