### ISSUE TITLE
Uncaught ReflectionException: Class config does not exist

### ISSUE THREAD

**Issue by athasamid** [brozot/Laravel-FCM#86]
hello, i got error after register FCMServiceProvider in bootstrap/app.php

`$app->register(LaravelFCM\FCMServiceProvider::class);`

error

> PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('config')
#1 vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('config')
#2 vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('config', Array)
#3 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\Container\Container->make('config', Array)
#4 vendor/laravel/framework/src/Illuminate/Container/Container.php(1195): Illuminate\Foundation in vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752 
Fatal error: Uncaught ReflectionException: Class config does not exist in vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('config')
#1 vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('config')
#2 vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('config', Array)
#3 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\Container\Container->make('config', Array)
#4 vendor/laravel/framework/src/Illuminate/Container/Container.php(1195): Illuminate\Foundation in vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752

Thanks

**Comment by brozot** [comment]
Hi, Try to copy config fileCopy

>the config file fcm.php manually from the directory /vendor/brozot/laravel-fcm/config to the directory /config (you may need to create this directory).

Best Regards,

**Comment by athasamid** [comment]
owh sorry, i've done this, it's my mistake, i add that line in laravel framework not in lumen ;)

**Comment by soha1410** [comment]
> umen ;

hi, can you please explain more how to solve the problem , i use laravel 5.6 and copy that line to bootstrap/app.php . where is the lumen file ?

**Comment by SachinBahukhandi** [comment]
Hi @brozot I did not get the **config** directory. We already have the config directory in **Laravel**!? Please help.
